import { readFileSync, writeFileSync, unlinkSync, existsSync, readdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const localesDir = resolve(root, "src", "i18n", "locales");
const todosDir = resolve(root, "docs", "localization_todo");

// Translations for all 46 keys across all 12 locales
const allTranslations = {
  "dashboard.scriptWidgetCapped": {
    de: "Zum Aktivieren klicken (max {{max}} aktive Widgets)",
    es: "Clic para activar (máx {{max}} widgets activos)",
    "es-MX": "Clic para activar (máx {{max}} widgets activos)",
    fr: "Cliquer pour activer (max {{max}} widgets actifs)",
    id: "Klik untuk mengaktifkan (maks {{max}} widget aktif)",
    it: "Clicca per attivare (max {{max}} widget attivi)",
    ja: "クリックして有効化（最大 {{max}} 個のアクティブウィジェット）",
    ko: "클릭하여 활성화 (최대 {{max}}개 활성 위젯)",
    "pt-BR": "Clique para ativar (máx {{max}} widgets ativos)",
    th: "คลิกเพื่อเปิดใช้งาน (สูงสุด {{max}} วิดเจ็ตที่ทำงาน)",
    "zh-CN": "点击激活（最多 {{max}} 个活动小组件）",
    "zh-TW": "點擊啟用（最多 {{max}} 個活動小工具）",
  },
  "dashboard.scriptWidgetFrameTitle": {
    de: "Dashboard-Skript-Widget",
    es: "Widget de script del Dashboard",
    "es-MX": "Widget de script del Dashboard",
    fr: "Widget de script du tableau de bord",
    id: "Widget skrip Dashboard",
    it: "Widget script Dashboard",
    ja: "ダッシュボード スクリプト ウィジェット",
    ko: "대시보드 스크립트 위젯",
    "pt-BR": "Widget de script do Dashboard",
    th: "วิดเจ็ตสคริปต์แดชบอร์ด",
    "zh-CN": "仪表板脚本小组件",
    "zh-TW": "儀表板指令碼小工具",
  },
  "dashboard.widgetLibraryLoadFailed": {
    de: "Widget-Bibliotheken konnten nicht geladen werden: {{error}}",
    es: "Error al cargar las bibliotecas de widgets: {{error}}",
    "es-MX": "Error al cargar las bibliotecas de widgets: {{error}}",
    fr: "Échec du chargement des bibliothèques de widgets : {{error}}",
    id: "Gagal memuat pustaka widget: {{error}}",
    it: "Impossibile caricare le librerie widget: {{error}}",
    ja: "ウィジェットライブラリの読み込みに失敗しました: {{error}}",
    ko: "위젯 라이브러리 로드 실패: {{error}}",
    "pt-BR": "Falha ao carregar bibliotecas de widgets: {{error}}",
    th: "โหลดไลบรารีวิดเจ็ตล้มเหลว: {{error}}",
    "zh-CN": "加载小组件库失败：{{error}}",
    "zh-TW": "載入小工具庫失敗：{{error}}",
  },
  "settings.refreshModels": {
    de: "Modelle aktualisieren",
    es: "Actualizar modelos",
    "es-MX": "Actualizar modelos",
    fr: "Actualiser les modèles",
    id: "Muat ulang model",
    it: "Aggiorna modelli",
    ja: "モデルを更新",
    ko: "모델 새로고침",
    "pt-BR": "Atualizar modelos",
    th: "รีเฟรชโมเดล",
    "zh-CN": "刷新模型",
    "zh-TW": "重新整理模型",
  },
  "settings.refreshingModels": {
    de: "Modelle werden aktualisiert",
    es: "Actualizando modelos",
    "es-MX": "Actualizando modelos",
    fr: "Actualisation des modèles",
    id: "Memuat ulang model",
    it: "Aggiornamento modelli",
    ja: "モデルを更新中",
    ko: "모델 새로고침 중",
    "pt-BR": "Atualizando modelos",
    th: "กำลังรีเฟรชโมเดล",
    "zh-CN": "正在刷新模型",
    "zh-TW": "正在重新整理模型",
  },
  "settings.modelListRefreshed": {
    de: "Modellliste aktualisiert.",
    es: "Lista de modelos actualizada.",
    "es-MX": "Lista de modelos actualizada.",
    fr: "Liste des modèles actualisée.",
    id: "Daftar model dimuat ulang.",
    it: "Elenco modelli aggiornato.",
    ja: "モデルリストが更新されました。",
    ko: "모델 목록이 새로고침되었습니다.",
    "pt-BR": "Lista de modelos atualizada.",
    th: "รีเฟรชรายการโมเดลแล้ว",
    "zh-CN": "模型列表已刷新。",
    "zh-TW": "模型清單已重新整理。",
  },
  "settings.copilotCliInstallHelp": {
    de: "Copilot CLI installieren",
    es: "Cómo obtener Copilot CLI",
    "es-MX": "Cómo obtener Copilot CLI",
    fr: "Comment obtenir Copilot CLI",
    id: "Cara mendapatkan Copilot CLI",
    it: "Come ottenere Copilot CLI",
    ja: "Copilot CLI の入手方法",
    ko: "Copilot CLI 설치 방법",
    "pt-BR": "Como obter o Copilot CLI",
    th: "วิธีรับ Copilot CLI",
    "zh-CN": "如何获取 Copilot CLI",
    "zh-TW": "如何取得 Copilot CLI",
  },
  "settings.dashboardPerformance": {
    de: "Leistung",
    es: "Rendimiento",
    "es-MX": "Rendimiento",
    fr: "Performance",
    id: "Kinerja",
    it: "Prestazioni",
    ja: "パフォーマンス",
    ko: "성능",
    "pt-BR": "Desempenho",
    th: "ประสิทธิภาพ",
    "zh-CN": "性能",
    "zh-TW": "效能",
  },
  "settings.dashboardMaxActiveScriptWidgets": {
    de: "Maximale aktive Skript-Widgets",
    es: "Límite de widgets de script activos",
    "es-MX": "Límite de widgets de script activos",
    fr: "Limite de widgets de script actifs",
    id: "Batas widget skrip aktif",
    it: "Limite widget script attivi",
    ja: "アクティブスクリプトウィジェットの上限",
    ko: "활성 스크립트 위젯 제한",
    "pt-BR": "Limite de widgets de script ativos",
    th: "ขีดจำกัดวิดเจ็ตสคริปต์ที่ทำงาน",
    "zh-CN": "活动脚本小组件上限",
    "zh-TW": "活動指令碼小工具上限",
  },
  "settings.dashboardMaxActiveScriptWidgetsHint": {
    de: "Maximale Anzahl von Skript-Widgets, die gleichzeitig ihr iframe auf einem Dashboard rendern. Überschüssige Widgets zeigen einen Platzhalter zum Aktivieren. Zulässiger Bereich {{min}}–{{max}}.",
    es: "Número máximo de widgets de script que muestran su iframe a la vez en un Dashboard. Los widgets excedentes muestran un marcador para activar. Rango permitido {{min}}–{{max}}.",
    "es-MX": "Número máximo de widgets de script que muestran su iframe a la vez en un Dashboard. Los widgets excedentes muestran un marcador para activar. Rango permitido {{min}}–{{max}}.",
    fr: "Nombre maximal de widgets de script qui affichent leur iframe simultanément sur un tableau de bord. Les widgets excédentaires affichent un espace réservé à activer. Plage autorisée {{min}}–{{max}}.",
    id: "Jumlah maksimum widget skrip yang merender iframe-nya sekaligus di Dashboard. Widget berlebih menampilkan placeholder klik-untuk-mengaktifkan. Rentang yang diizinkan {{min}}–{{max}}.",
    it: "Numero massimo di widget script che visualizzano il proprio iframe contemporaneamente in un Dashboard. I widget in eccesso mostrano un segnaposto clicca-per-attivare. Intervallo consentito {{min}}–{{max}}.",
    ja: "ダッシュボードで同時に iframe をレンダリングするスクリプトウィジェットの最大数。超過したウィジェットにはクリックして有効化するプレースホルダーが表示されます。許容範囲 {{min}}–{{max}}。",
    ko: "대시보드에서 한 번에 iframe을 렌더링하는 최대 스크립트 위젯 수입니다. 초과 위젯은 클릭하여 활성화 플레이스홀더를 표시합니다. 허용 범위 {{min}}–{{max}}.",
    "pt-BR": "Número máximo de widgets de script que renderizam seu iframe de uma vez em um Dashboard. Widgets excedentes mostram um espaço reservado para ativar. Intervalo permitido {{min}}–{{max}}.",
    th: "จำนวนสูงสุดของวิดเจ็ตสคริปต์ที่แสดงผล iframe พร้อมกันบนแดชบอร์ด วิดเจ็ตที่เกินจะแสดงตัวยึดคลิกเพื่อเปิดใช้งาน ช่วงที่อนุญาต {{min}}–{{max}}",
    "zh-CN": "仪表板上同时渲染其 iframe 的脚本小组件最大数量。超出的小组件将显示点击激活占位符。允许范围 {{min}}–{{max}}。",
    "zh-TW": "儀表板上同時呈現其 iframe 的指令碼小工具最大數量。超出的小工具會顯示點擊啟用預留位置。允許範圍 {{min}}–{{max}}。",
  },
  "settings.mcpServersTitle": {
    de: "Remote MCP-Server",
    es: "Servidores MCP remotos",
    "es-MX": "Servidores MCP remotos",
    fr: "Serveurs MCP distants",
    id: "Server MCP jarak jauh",
    it: "Server MCP remoti",
    ja: "リモート MCP サーバー",
    ko: "원격 MCP 서버",
    "pt-BR": "Servidores MCP remotos",
    th: "เซิร์ฟเวอร์ MCP ระยะไกล",
    "zh-CN": "远程 MCP 服务器",
    "zh-TW": "遠端 MCP 伺服器",
  },
  "settings.mcpServersHint": {
    de: "Verbinden Sie sich mit Remote Model Context Protocol-Servern, damit der KI-Assistent und Dashboard-Widgets deren Tools aufrufen können. KKTerm unterstützt nur HTTP-Streamable-MCP-Server; stdio-Konfigurationen, die lokale Prozesse starten, werden nicht unterstützt.",
    es: "Conéctese a servidores remotos del Model Context Protocol para que el asistente de IA y los widgets del Dashboard puedan usar sus herramientas. KKTerm solo admite servidores MCP HTTP transmitibles; no se admiten configuraciones stdio que ejecuten procesos locales.",
    "es-MX": "Conéctese a servidores remotos del Model Context Protocol para que el asistente de IA y los widgets del Dashboard puedan usar sus herramientas. KKTerm solo admite servidores MCP HTTP transmitibles; no se admiten configuraciones stdio que ejecuten procesos locales.",
    fr: "Connectez-vous à des serveurs Model Context Protocol distants pour que l'assistant IA et les widgets du tableau de bord puissent appeler leurs outils. KKTerm prend uniquement en charge les serveurs MCP HTTP streamable ; les configurations stdio qui lancent des processus locaux ne sont pas prises en charge.",
    id: "Hubungkan ke server Model Context Protocol jarak jauh agar asisten AI dan widget Dashboard dapat memanggil alat mereka. KKTerm hanya mendukung server MCP HTTP streamable; konfigurasi stdio yang menjalankan proses lokal tidak didukung.",
    it: "Connettiti a server Model Context Protocol remoti in modo che l'assistente AI e i widget del Dashboard possano chiamare i loro strumenti. KKTerm supporta solo server MCP HTTP streamable; le configurazioni stdio che avviano processi locali non sono supportate.",
    ja: "リモート Model Context Protocol サーバーに接続して、AI アシスタントとダッシュボードウィジェットがそのツールを呼び出せるようにします。KKTerm は HTTP ストリーミング可能な MCP サーバーのみをサポートし、ローカルプロセスを起動する stdio 構成はサポートされません。",
    ko: "원격 Model Context Protocol 서버에 연결하여 AI 어시스턴트와 대시보드 위젯이 해당 도구를 호출할 수 있도록 합니다. KKTerm은 HTTP 스트리밍 가능한 MCP 서버만 지원하며, 로컬 프로세스를 생성하는 stdio 구성은 지원되지 않습니다.",
    "pt-BR": "Conecte-se a servidores remotos do Model Context Protocol para que o assistente de IA e os widgets do Dashboard possam usar suas ferramentas. O KKTerm oferece suporte apenas a servidores MCP HTTP transmissíveis; configurações stdio que executam processos locais não são suportadas.",
    th: "เชื่อมต่อกับเซิร์ฟเวอร์ Model Context Protocol ระยะไกลเพื่อให้ผู้ช่วย AI และวิดเจ็ตแดชบอร์ดสามารถเรียกใช้เครื่องมือของพวกเขาได้ KKTerm รองรับเฉพาะเซิร์ฟเวอร์ MCP แบบ HTTP สตรีมได้เท่านั้น ไม่รองรับการกำหนดค่า stdio ที่เรียกใช้โปรเซสภายใน",
    "zh-CN": "连接到远程 Model Context Protocol 服务器，以便 AI 助手和仪表板小组件可以调用它们的工具。KKTerm 仅支持 HTTP 流式 MCP 服务器；不支持启动本地进程的 stdio 配置。",
    "zh-TW": "連接到遠端 Model Context Protocol 伺服器，以便 AI 助手和儀表板小工具可以呼叫它們的工具。KKTerm 僅支援 HTTP 串流 MCP 伺服器；不支援啟動本機處理程序的 stdio 設定。",
  },
  "settings.mcpServersEmpty": {
    de: "Keine MCP-Server konfiguriert.",
    es: "No hay servidores MCP configurados.",
    "es-MX": "No hay servidores MCP configurados.",
    fr: "Aucun serveur MCP configuré.",
    id: "Tidak ada server MCP yang dikonfigurasi.",
    it: "Nessun server MCP configurato.",
    ja: "MCP サーバーが設定されていません。",
    ko: "구성된 MCP 서버가 없습니다.",
    "pt-BR": "Nenhum servidor MCP configurado.",
    th: "ยังไม่ได้กำหนดค่าเซิร์ฟเวอร์ MCP",
    "zh-CN": "未配置 MCP 服务器。",
    "zh-TW": "尚未設定 MCP 伺服器。",
  },
  "settings.mcpAddServer": {
    de: "MCP-Server hinzufügen",
    es: "Agregar servidor MCP",
    "es-MX": "Agregar servidor MCP",
    fr: "Ajouter un serveur MCP",
    id: "Tambah server MCP",
    it: "Aggiungi server MCP",
    ja: "MCP サーバーを追加",
    ko: "MCP 서버 추가",
    "pt-BR": "Adicionar servidor MCP",
    th: "เพิ่มเซิร์ฟเวอร์ MCP",
    "zh-CN": "添加 MCP 服务器",
    "zh-TW": "新增 MCP 伺服器",
  },
  "settings.mcpDeleteServer": {
    de: "MCP-Server entfernen",
    es: "Eliminar servidor MCP",
    "es-MX": "Eliminar servidor MCP",
    fr: "Supprimer le serveur MCP",
    id: "Hapus server MCP",
    it: "Rimuovi server MCP",
    ja: "MCP サーバーを削除",
    ko: "MCP 서버 제거",
    "pt-BR": "Remover servidor MCP",
    th: "ลบเซิร์ฟเวอร์ MCP",
    "zh-CN": "移除 MCP 服务器",
    "zh-TW": "移除 MCP 伺服器",
  },
  "settings.mcpDeleteConfirmBody": {
    de: 'Den MCP-Server "{{name}}" entfernen? Das Auth-Secret wird aus dem Schlüsselbund gelöscht und Widgets, die diesen Server referenzieren, schlagen fehl, bis sie neu konfiguriert werden.',
    es: '¿Eliminar el servidor MCP "{{name}}"? Su secreto de autenticación se eliminará del llavero y los widgets que hagan referencia a este servidor fallarán hasta que se reconfiguren.',
    "es-MX": '¿Eliminar el servidor MCP "{{name}}"? Su secreto de autenticación se eliminará del llavero y los widgets que hagan referencia a este servidor fallarán hasta que se reconfiguren.',
    fr: 'Supprimer le serveur MCP « {{name}} » ? Son secret d\'authentification sera supprimé du trousseau et les widgets qui référencent ce serveur échoueront jusqu\'à reconfiguration.',
    id: 'Hapus server MCP "{{name}}"? Rahasia autentikasinya akan dihapus dari keychain dan widget yang mereferensikan server ini akan gagal hingga dikonfigurasi ulang.',
    it: 'Rimuovere il server MCP "{{name}}"? Il suo segreto di autenticazione verrà eliminato dal portachiavi e i widget che fanno riferimento a questo server falliranno fino a quando non verranno riconfigurati.',
    ja: 'MCP サーバー「{{name}}」を削除しますか？認証シークレットはキーチェーンから削除され、このサーバーを参照するウィジェットは再構成されるまで失敗します。',
    ko: 'MCP 서버 "{{name}}"을(를) 제거하시겠습니까? 인증 비밀이 키체인에서 삭제되며 이 서버를 참조하는 위젯은 재구성될 때까지 실패합니다.',
    "pt-BR": 'Remover o servidor MCP "{{name}}"? Seu segredo de autenticação será excluído do chaveiro e os widgets que referenciam este servidor falharão até serem reconfigurados.',
    th: 'ลบเซิร์ฟเวอร์ MCP "{{name}}" หรือไม่ ข้อมูลลับการตรวจสอบสิทธิ์จะถูกลบออกจากพวงกุญแจและวิดเจ็ตที่อ้างอิงเซิร์ฟเวอร์นี้จะล้มเหลวจนกว่าจะกำหนดค่าใหม่',
    "zh-CN": '移除 MCP 服务器「{{name}}」？其认证密钥将从密钥链中删除，引用此服务器的小组件在重新配置之前将失败。',
    "zh-TW": '移除 MCP 伺服器「{{name}}」？其驗證密鑰將從金鑰鏈中刪除，引用此伺服器的小工具在重新設定之前將會失敗。',
  },
  "settings.mcpRefreshTools": {
    de: "Tools aktualisieren",
    es: "Actualizar herramientas",
    "es-MX": "Actualizar herramientas",
    fr: "Actualiser les outils",
    id: "Muat ulang alat",
    it: "Aggiorna strumenti",
    ja: "ツールを更新",
    ko: "도구 새로고침",
    "pt-BR": "Atualizar ferramentas",
    th: "รีเฟรชเครื่องมือ",
    "zh-CN": "刷新工具",
    "zh-TW": "重新整理工具",
  },
  "settings.mcpToolsCount": {
    de: "{{count}} Tools",
    es: "{{count}} herramientas",
    "es-MX": "{{count}} herramientas",
    fr: "{{count}} outils",
    id: "{{count}} alat",
    it: "{{count}} strumenti",
    ja: "{{count}} 個のツール",
    ko: "{{count}}개 도구",
    "pt-BR": "{{count}} ferramentas",
    th: "{{count}} เครื่องมือ",
    "zh-CN": "{{count}} 个工具",
    "zh-TW": "{{count}} 個工具",
  },
  "settings.mcpToolsCount_one": {
    de: "{{count}} Tool",
    es: "{{count}} herramienta",
    "es-MX": "{{count}} herramienta",
    fr: "{{count}} outil",
    id: "{{count}} alat",
    it: "{{count}} strumento",
    ja: "{{count}} 個のツール",
    ko: "{{count}}개 도구",
    "pt-BR": "{{count}} ferramenta",
    th: "{{count}} เครื่องมือ",
    "zh-CN": "{{count}} 个工具",
    "zh-TW": "{{count}} 個工具",
  },
  "settings.mcpStatusOk": {
    de: "Verbunden",
    es: "Conectado",
    "es-MX": "Conectado",
    fr: "Connecté",
    id: "Terhubung",
    it: "Connesso",
    ja: "接続済み",
    ko: "연결됨",
    "pt-BR": "Conectado",
    th: "เชื่อมต่อแล้ว",
    "zh-CN": "已连接",
    "zh-TW": "已連線",
  },
  "settings.mcpStatusUnreachable": {
    de: "Nicht erreichbar",
    es: "Inaccesible",
    "es-MX": "Inaccesible",
    fr: "Inaccessible",
    id: "Tidak terjangkau",
    it: "Irraggiungibile",
    ja: "到達不能",
    ko: "연결 불가",
    "pt-BR": "Inacessível",
    th: "ไม่สามารถเข้าถึงได้",
    "zh-CN": "无法访问",
    "zh-TW": "無法存取",
  },
  "settings.mcpStatusAuthError": {
    de: "Auth-Fehler",
    es: "Error de autenticación",
    "es-MX": "Error de autenticación",
    fr: "Erreur d'authentification",
    id: "Kesalahan autentikasi",
    it: "Errore di autenticazione",
    ja: "認証エラー",
    ko: "인증 오류",
    "pt-BR": "Erro de autenticação",
    th: "ข้อผิดพลาดการตรวจสอบสิทธิ์",
    "zh-CN": "认证错误",
    "zh-TW": "驗證錯誤",
  },
  "settings.mcpStatusProtocolError": {
    de: "Protokollfehler",
    es: "Error de protocolo",
    "es-MX": "Error de protocolo",
    fr: "Erreur de protocole",
    id: "Kesalahan protokol",
    it: "Errore di protocollo",
    ja: "プロトコルエラー",
    ko: "프로토콜 오류",
    "pt-BR": "Erro de protocolo",
    th: "ข้อผิดพลาดโปรโตคอล",
    "zh-CN": "协议错误",
    "zh-TW": "通訊協定錯誤",
  },
  "settings.mcpStatusUnknown": {
    de: "Noch nicht geprüft",
    es: "Aún no verificado",
    "es-MX": "Aún no verificado",
    fr: "Pas encore sondé",
    id: "Belum diperiksa",
    it: "Non ancora verificato",
    ja: "未確認",
    ko: "아직 확인되지 않음",
    "pt-BR": "Ainda não verificado",
    th: "ยังไม่ได้ตรวจสอบ",
    "zh-CN": "尚未探测",
    "zh-TW": "尚未探測",
  },
  "settings.mcpAuthBadge": {
    de: "Auth",
    es: "Auth",
    "es-MX": "Auth",
    fr: "Auth",
    id: "Auth",
    it: "Auth",
    ja: "認証",
    ko: "인증",
    "pt-BR": "Auth",
    th: "การตรวจสอบสิทธิ์",
    "zh-CN": "认证",
    "zh-TW": "驗證",
  },
  "settings.mcpPasteHint": {
    de: 'Fügen Sie eine HTTP-MCP-Server-JSON-Konfiguration ein. Übliche Formate funktionieren: ein einzelnes { "url": ..., "headers": ... } Objekt oder eine Claude Desktop-artige { "mcpServers": { "name": { ... } } } Map.',
    es: 'Pegue una configuración JSON de servidor MCP HTTP. Funcionan formatos comunes: un objeto simple { "url": ..., "headers": ... } o un mapa estilo Claude Desktop { "mcpServers": { "name": { ... } } }.',
    "es-MX": 'Pegue una configuración JSON de servidor MCP HTTP. Funcionan formatos comunes: un objeto simple { "url": ..., "headers": ... } o un mapa estilo Claude Desktop { "mcpServers": { "name": { ... } } }.',
    fr: 'Collez une configuration JSON de serveur MCP HTTP. Les formats courants fonctionnent : un objet simple { "url": ..., "headers": ... } ou une map style Claude Desktop { "mcpServers": { "name": { ... } } }.',
    id: 'Tempel konfigurasi JSON server MCP HTTP. Bentuk umum berfungsi: objek tunggal { "url": ..., "headers": ... } atau peta gaya Claude Desktop { "mcpServers": { "name": { ... } } }.',
    it: 'Incolla una configurazione JSON del server MCP HTTP. I formati comuni funzionano: un singolo oggetto { "url": ..., "headers": ... } o una mappa in stile Claude Desktop { "mcpServers": { "name": { ... } } }.',
    ja: 'HTTP MCP サーバーの JSON 設定を貼り付けます。一般的な形式が機能します：単一の { "url": ..., "headers": ... } オブジェクト、または Claude Desktop スタイルの { "mcpServers": { "name": { ... } } } マップ。',
    ko: 'HTTP MCP 서버 JSON 구성을 붙여넣으세요. 일반적인 형식이 작동합니다: 단일 { "url": ..., "headers": ... } 객체 또는 Claude Desktop 스타일 { "mcpServers": { "name": { ... } } } 맵.',
    "pt-BR": 'Cole uma configuração JSON de servidor MCP HTTP. Formatos comuns funcionam: um único objeto { "url": ..., "headers": ... } ou um mapa estilo Claude Desktop { "mcpServers": { "name": { ... } } }.',
    th: 'วางการกำหนดค่า JSON ของเซิร์ฟเวอร์ MCP HTTP รูปแบบทั่วไปที่ใช้งานได้: ออบเจ็กต์เดี่ยว { "url": ..., "headers": ... } หรือแผนที่สไตล์ Claude Desktop { "mcpServers": { "name": { ... } } }',
    "zh-CN": '粘贴 HTTP MCP 服务器 JSON 配置。常见格式均可使用：单个 { "url": ..., "headers": ... } 对象或 Claude Desktop 风格的 { "mcpServers": { "name": { ... } } } 映射。',
    "zh-TW": '貼上 HTTP MCP 伺服器 JSON 設定。常見格式均可使用：單一 { "url": ..., "headers": ... } 物件或 Claude Desktop 風格的 { "mcpServers": { "name": { ... } } } 對應。',
  },
  "settings.mcpPastePlaceholder": {
    de: '{\n  "url": "https://example.com/mcp",\n  "headers": {\n    "Authorization": "Bearer ..."\n  }\n}',
    es: '{\n  "url": "https://example.com/mcp",\n  "headers": {\n    "Authorization": "Bearer ..."\n  }\n}',
    "es-MX": '{\n  "url": "https://example.com/mcp",\n  "headers": {\n    "Authorization": "Bearer ..."\n  }\n}',
    fr: '{\n  "url": "https://example.com/mcp",\n  "headers": {\n    "Authorization": "Bearer ..."\n  }\n}',
    id: '{\n  "url": "https://example.com/mcp",\n  "headers": {\n    "Authorization": "Bearer ..."\n  }\n}',
    it: '{\n  "url": "https://example.com/mcp",\n  "headers": {\n    "Authorization": "Bearer ..."\n  }\n}',
    ja: '{\n  "url": "https://example.com/mcp",\n  "headers": {\n    "Authorization": "Bearer ..."\n  }\n}',
    ko: '{\n  "url": "https://example.com/mcp",\n  "headers": {\n    "Authorization": "Bearer ..."\n  }\n}',
    "pt-BR": '{\n  "url": "https://example.com/mcp",\n  "headers": {\n    "Authorization": "Bearer ..."\n  }\n}',
    th: '{\n  "url": "https://example.com/mcp",\n  "headers": {\n    "Authorization": "Bearer ..."\n  }\n}',
    "zh-CN": '{\n  "url": "https://example.com/mcp",\n  "headers": {\n    "Authorization": "Bearer ..."\n  }\n}',
    "zh-TW": '{\n  "url": "https://example.com/mcp",\n  "headers": {\n    "Authorization": "Bearer ..."\n  }\n}',
  },
  "settings.mcpPasteContinue": {
    de: "Weiter",
    es: "Continuar",
    "es-MX": "Continuar",
    fr: "Continuer",
    id: "Lanjutkan",
    it: "Continua",
    ja: "続行",
    ko: "계속",
    "pt-BR": "Continuar",
    th: "ดำเนินการต่อ",
    "zh-CN": "继续",
    "zh-TW": "繼續",
  },
  "settings.mcpConfirmHint": {
    de: "Überprüfen Sie die analysierte Konfiguration vor dem Speichern. KKTerm prüft die Tool-Liste des Servers sofort nach der Erstellung.",
    es: "Revise la configuración analizada antes de guardar. KKTerm sondeará la lista de herramientas del servidor inmediatamente después de la creación.",
    "es-MX": "Revise la configuración analizada antes de guardar. KKTerm sondeará la lista de herramientas del servidor inmediatamente después de la creación.",
    fr: "Vérifiez la configuration analysée avant d'enregistrer. KKTerm sondera la liste d'outils du serveur immédiatement après la création.",
    id: "Tinjau konfigurasi yang diurai sebelum menyimpan. KKTerm akan memeriksa daftar alat server segera setelah pembuatan.",
    it: "Rivedi la configurazione analizzata prima di salvare. KKTerm sonderà l'elenco degli strumenti del server subito dopo la creazione.",
    ja: "保存前に解析された設定を確認してください。KKTerm は作成後すぐにサーバーのツールリストをプローブします。",
    ko: "저장하기 전에 구문 분석된 구성을 검토하세요. KKTerm은 생성 직후 서버의 도구 목록을 즉시 프로브합니다.",
    "pt-BR": "Revise a configuração analisada antes de salvar. O KKTerm sondará a lista de ferramentas do servidor imediatamente após a criação.",
    th: "ตรวจสอบการกำหนดค่าที่แยกวิเคราะห์ก่อนบันทึก KKTerm จะตรวจสอบรายการเครื่องมือของเซิร์ฟเวอร์ทันทีหลังจากสร้าง",
    "zh-CN": "保存前请检查解析后的配置。KKTerm 将在创建后立即探测服务器的工具列表。",
    "zh-TW": "儲存前請檢查解析後的設定。KKTerm 將在建立後立即探測伺服器的工具清單。",
  },
  "settings.mcpCreateServer": {
    de: "MCP-Server speichern",
    es: "Guardar servidor MCP",
    "es-MX": "Guardar servidor MCP",
    fr: "Enregistrer le serveur MCP",
    id: "Simpan server MCP",
    it: "Salva server MCP",
    ja: "MCP サーバーを保存",
    ko: "MCP 서버 저장",
    "pt-BR": "Salvar servidor MCP",
    th: "บันทึกเซิร์ฟเวอร์ MCP",
    "zh-CN": "保存 MCP 服务器",
    "zh-TW": "儲存 MCP 伺服器",
  },
  "settings.mcpServerName": {
    de: "Name",
    es: "Nombre",
    "es-MX": "Nombre",
    fr: "Nom",
    id: "Nama",
    it: "Nome",
    ja: "名前",
    ko: "이름",
    "pt-BR": "Nome",
    th: "ชื่อ",
    "zh-CN": "名称",
    "zh-TW": "名稱",
  },
  "settings.mcpServerUrl": {
    de: "URL",
    es: "URL",
    "es-MX": "URL",
    fr: "URL",
    id: "URL",
    it: "URL",
    ja: "URL",
    ko: "URL",
    "pt-BR": "URL",
    th: "URL",
    "zh-CN": "URL",
    "zh-TW": "URL",
  },
  "settings.mcpHeadersLabel": {
    de: "Headers",
    es: "Encabezados",
    "es-MX": "Encabezados",
    fr: "En-têtes",
    id: "Header",
    it: "Intestazioni",
    ja: "ヘッダー",
    ko: "헤더",
    "pt-BR": "Cabeçalhos",
    th: "ส่วนหัว",
    "zh-CN": "标头",
    "zh-TW": "標頭",
  },
  "settings.mcpDetectedSecretHint": {
    de: "Ein Authentifizierungs-Header wurde erkannt. Das Token wird im OS-Schlüsselbund gespeichert; nur ein {SECRET}-Platzhalter wird in der SQLite-Konfiguration gespeichert.",
    es: "Se detectó un encabezado de autenticación. El token se almacenará en el llavero del SO; solo se guarda un marcador {SECRET} en la configuración SQLite.",
    "es-MX": "Se detectó un encabezado de autenticación. El token se almacenará en el llavero del SO; solo se guarda un marcador {SECRET} en la configuración SQLite.",
    fr: "Un en-tête d'authentification a été détecté. Le jeton sera stocké dans le trousseau du système d'exploitation ; seul un espace réservé {SECRET} est conservé dans la configuration SQLite.",
    id: "Header autentikasi terdeteksi. Token akan disimpan di keychain OS; hanya placeholder {SECRET} yang disimpan di konfigurasi SQLite.",
    it: "È stata rilevata un'intestazione di autenticazione. Il token verrà archiviato nel portachiavi del sistema operativo; solo un segnaposto {SECRET} viene conservato nella configurazione SQLite.",
    ja: "認証ヘッダーが検出されました。トークンは OS キーチェーンに保存され、SQLite 設定には {SECRET} プレースホルダーのみが保持されます。",
    ko: "인증 헤더가 감지되었습니다. 토큰은 OS 키체인에 저장되며 SQLite 구성에는 {SECRET} 자리 표시자만 유지됩니다.",
    "pt-BR": "Um cabeçalho de autenticação foi detectado. O token será armazenado no chaveiro do SO; apenas um espaço reservado {SECRET} é mantido na configuração SQLite.",
    th: "ตรวจพบส่วนหัวการตรวจสอบสิทธิ์ โทเค็นจะถูกเก็บไว้ในพวงกุญแจของระบบปฏิบัติการ เฉพาะตัวยึด {SECRET} เท่านั้นที่คงอยู่ในการกำหนดค่า SQLite",
    "zh-CN": "检测到认证标头。令牌将存储在操作系统密钥链中；SQLite 配置中仅保留 {SECRET} 占位符。",
    "zh-TW": "偵測到驗證標頭。權杖將儲存在作業系統金鑰鏈中；SQLite 設定中僅保留 {SECRET} 預留位置。",
  },
  "settings.mcpSecretHeaderName": {
    de: "Auth-Header",
    es: "Encabezado de autenticación",
    "es-MX": "Encabezado de autenticación",
    fr: "En-tête d'authentification",
    id: "Header autentikasi",
    it: "Intestazione di autenticazione",
    ja: "認証ヘッダー",
    ko: "인증 헤더",
    "pt-BR": "Cabeçalho de autenticação",
    th: "ส่วนหัวการตรวจสอบสิทธิ์",
    "zh-CN": "认证标头",
    "zh-TW": "驗證標頭",
  },
  "settings.mcpSecretValueTemplate": {
    de: "Auth-Wert-Vorlage",
    es: "Plantilla de valor de autenticación",
    "es-MX": "Plantilla de valor de autenticación",
    fr: "Modèle de valeur d'authentification",
    id: "Templat nilai autentikasi",
    it: "Modello valore di autenticazione",
    ja: "認証値テンプレート",
    ko: "인증 값 템플릿",
    "pt-BR": "Modelo de valor de autenticação",
    th: "เทมเพลตค่าการตรวจสอบสิทธิ์",
    "zh-CN": "认证值模板",
    "zh-TW": "驗證值範本",
  },
  "settings.mcpSecretValue": {
    de: "Auth-Secret (im Schlüsselbund gespeichert)",
    es: "Secreto de autenticación (guardado en el llavero)",
    "es-MX": "Secreto de autenticación (guardado en el llavero)",
    fr: "Secret d'authentification (stocké dans le trousseau)",
    id: "Rahasia autentikasi (disimpan di keychain)",
    it: "Segreto di autenticazione (archiviato nel portachiavi)",
    ja: "認証シークレット（キーチェーンに保存）",
    ko: "인증 비밀 (키체인에 저장됨)",
    "pt-BR": "Segredo de autenticação (armazenado no chaveiro)",
    th: "ข้อมูลลับการตรวจสอบสิทธิ์ (เก็บในพวงกุญแจ)",
    "zh-CN": "认证密钥（存储在密钥链中）",
    "zh-TW": "驗證密鑰（儲存在金鑰鏈中）",
  },
  "settings.mcpAddInvalidJson": {
    de: "JSON konnte nicht analysiert werden. Überprüfen Sie, ob der eingefügte Text gültig ist.",
    es: "No se pudo analizar el JSON. Verifique que el texto pegado sea válido.",
    "es-MX": "No se pudo analizar el JSON. Verifique que el texto pegado sea válido.",
    fr: "Impossible d'analyser le JSON. Vérifiez que le texte collé est valide.",
    id: "Tidak dapat mengurai JSON. Periksa apakah teks yang ditempel valid.",
    it: "Impossibile analizzare il JSON. Verifica che il testo incollato sia valido.",
    ja: "JSON を解析できませんでした。貼り付けたテキストが有効か確認してください。",
    ko: "JSON을 구문 분석할 수 없습니다. 붙여넣은 텍스트가 유효한지 확인하세요.",
    "pt-BR": "Não foi possível analisar o JSON. Verifique se o texto colado é válido.",
    th: "ไม่สามารถแยกวิเคราะห์ JSON ได้ ตรวจสอบว่าข้อความที่วางถูกต้อง",
    "zh-CN": "无法解析 JSON。请检查粘贴的文本是否有效。",
    "zh-TW": "無法解析 JSON。請檢查貼上的文字是否有效。",
  },
  "settings.mcpAddInvalidShape": {
    de: "Die Konfiguration muss ein JSON-Objekt mit mindestens einem url-Feld sein.",
    es: "La configuración debe ser un objeto JSON con al menos un campo url.",
    "es-MX": "La configuración debe ser un objeto JSON con al menos un campo url.",
    fr: "La configuration doit être un objet JSON avec au moins un champ url.",
    id: "Konfigurasi harus berupa objek JSON dengan setidaknya field url.",
    it: "La configurazione deve essere un oggetto JSON con almeno un campo url.",
    ja: "設定は少なくとも url フィールドを持つ JSON オブジェクトである必要があります。",
    ko: "구성은 최소한 url 필드가 있는 JSON 객체여야 합니다.",
    "pt-BR": "A configuração deve ser um objeto JSON com pelo menos um campo url.",
    th: "การกำหนดค่าต้องเป็นออบเจ็กต์ JSON ที่มีฟิลด์ url อย่างน้อย",
    "zh-CN": "配置必须是至少包含 url 字段的 JSON 对象。",
    "zh-TW": "設定必須是至少包含 url 欄位的 JSON 物件。",
  },
  "settings.mcpAddNoServers": {
    de: "Die mcpServers-Map ist leer.",
    es: "El mapa mcpServers está vacío.",
    "es-MX": "El mapa mcpServers está vacío.",
    fr: "La map mcpServers est vide.",
    id: "Peta mcpServers kosong.",
    it: "La mappa mcpServers è vuota.",
    ja: "mcpServers マップが空です。",
    ko: "mcpServers 맵이 비어 있습니다.",
    "pt-BR": "O mapa mcpServers está vazio.",
    th: "แผนที่ mcpServers ว่างเปล่า",
    "zh-CN": "mcpServers 映射为空。",
    "zh-TW": "mcpServers 對應為空。",
  },
  "settings.mcpAddMissingUrl": {
    de: "Erforderliches url-Feld fehlt.",
    es: "Falta el campo url requerido.",
    "es-MX": "Falta el campo url requerido.",
    fr: "Champ url requis manquant.",
    id: "Field url yang diperlukan tidak ada.",
    it: "Campo url obbligatorio mancante.",
    ja: "必須の url フィールドがありません。",
    ko: "필수 url 필드가 없습니다.",
    "pt-BR": "Campo url obrigatório ausente.",
    th: "ไม่มีฟิลด์ url ที่จำเป็น",
    "zh-CN": "缺少必需的 url 字段。",
    "zh-TW": "缺少必要的 url 欄位。",
  },
  "settings.mcpAddStdioUnsupported": {
    de: "Dieser MCP-Server verwendet lokale Prozessausführung (stdio-Transport), die KKTerm nicht unterstützt.",
    es: "Este servidor MCP utiliza ejecución de procesos locales (transporte stdio), que KKTerm no admite.",
    "es-MX": "Este servidor MCP utiliza ejecución de procesos locales (transporte stdio), que KKTerm no admite.",
    fr: "Ce serveur MCP utilise l'exécution de processus locaux (transport stdio), ce que KKTerm ne prend pas en charge.",
    id: "Server MCP ini menggunakan eksekusi proses lokal (transport stdio), yang tidak didukung KKTerm.",
    it: "Questo server MCP utilizza l'esecuzione di processi locali (trasporto stdio), che KKTerm non supporta.",
    ja: "この MCP サーバーはローカルプロセス実行（stdio トランスポート）を使用していますが、KKTerm はこれをサポートしていません。",
    ko: "이 MCP 서버는 KKTerm이 지원하지 않는 로컬 프로세스 실행(stdio 전송)을 사용합니다.",
    "pt-BR": "Este servidor MCP usa execução de processos locais (transporte stdio), que o KKTerm não oferece suporte.",
    th: "เซิร์ฟเวอร์ MCP นี้ใช้การเรียกใช้โปรเซสภายใน (การขนส่ง stdio) ซึ่ง KKTerm ไม่รองรับ",
    "zh-CN": "此 MCP 服务器使用本地进程执行（stdio 传输），KKTerm 不支持。",
    "zh-TW": "此 MCP 伺服器使用本機處理程序執行（stdio 傳輸），KKTerm 不支援。",
  },
  "settings.mcpStdioGuidance": {
    de: "Suchen Sie einen HTTP-basierten MCP-Endpunkt desselben Anbieters oder prüfen Sie dessen Dokumentation auf eine gehostete Option.",
    es: "Busque un endpoint MCP basado en HTTP del mismo proveedor o consulte su documentación para una opción alojada.",
    "es-MX": "Busque un endpoint MCP basado en HTTP del mismo proveedor o consulte su documentación para una opción alojada.",
    fr: "Recherchez un point de terminaison MCP basé sur HTTP du même fournisseur ou consultez sa documentation pour une option hébergée.",
    id: "Cari endpoint MCP berbasis HTTP dari penyedia yang sama, atau periksa dokumentasi mereka untuk opsi yang dihosting.",
    it: "Cerca un endpoint MCP basato su HTTP dello stesso provider o consulta la loro documentazione per un'opzione ospitata.",
    ja: "同じプロバイダーの HTTP ベースの MCP エンドポイントを探すか、ホスト型オプションについてドキュメントを確認してください。",
    ko: "동일한 제공업체의 HTTP 기반 MCP 엔드포인트를 찾거나 호스팅된 옵션에 대한 설명서를 확인하세요.",
    "pt-BR": "Procure um endpoint MCP baseado em HTTP do mesmo provedor ou verifique a documentação para uma opção hospedada.",
    th: "ค้นหาปลายทาง MCP แบบ HTTP จากผู้ให้บริการเดียวกัน หรือตรวจสอบเอกสารสำหรับตัวเลือกแบบโฮสต์",
    "zh-CN": "查找同一提供商的基于 HTTP 的 MCP 端点，或查看其文档以获取托管选项。",
    "zh-TW": "尋找相同提供者的 HTTP 型 MCP 端點，或查看其文件以取得託管選項。",
  },
  "settings.mcpErrorNotFound": {
    de: "MCP-Server nicht gefunden.",
    es: "Servidor MCP no encontrado.",
    "es-MX": "Servidor MCP no encontrado.",
    fr: "Serveur MCP introuvable.",
    id: "Server MCP tidak ditemukan.",
    it: "Server MCP non trovato.",
    ja: "MCP サーバーが見つかりません。",
    ko: "MCP 서버를 찾을 수 없습니다.",
    "pt-BR": "Servidor MCP não encontrado.",
    th: "ไม่พบเซิร์ฟเวอร์ MCP",
    "zh-CN": "未找到 MCP 服务器。",
    "zh-TW": "找不到 MCP 伺服器。",
  },
  "settings.mcpErrorDuplicateName": {
    de: "Ein MCP-Server mit diesem Namen existiert bereits.",
    es: "Ya existe un servidor MCP con ese nombre.",
    "es-MX": "Ya existe un servidor MCP con ese nombre.",
    fr: "Un serveur MCP avec ce nom existe déjà.",
    id: "Server MCP dengan nama tersebut sudah ada.",
    it: "Un server MCP con quel nome esiste già.",
    ja: "その名前の MCP サーバーは既に存在します。",
    ko: "해당 이름의 MCP 서버가 이미 존재합니다.",
    "pt-BR": "Já existe um servidor MCP com esse nome.",
    th: "มีเซิร์ฟเวอร์ MCP ที่ชื่อนั้นอยู่แล้ว",
    "zh-CN": "该名称的 MCP 服务器已存在。",
    "zh-TW": "該名稱的 MCP 伺服器已存在。",
  },
  "settings.mcpErrorKeychain": {
    de: "OS-Schlüsselbund ist nicht verfügbar; Secrets können nicht gespeichert werden.",
    es: "El llavero del SO no está disponible; no se pueden almacenar secretos.",
    "es-MX": "El llavero del SO no está disponible; no se pueden almacenar secretos.",
    fr: "Le trousseau du système d'exploitation est indisponible ; les secrets ne peuvent pas être stockés.",
    id: "Keychain OS tidak tersedia; rahasia tidak dapat disimpan.",
    it: "Il portachiavi del sistema operativo non è disponibile; i segreti non possono essere archiviati.",
    ja: "OS キーチェーンが利用できません。シークレットを保存できません。",
    ko: "OS 키체인을 사용할 수 없습니다. 비밀을 저장할 수 없습니다.",
    "pt-BR": "O chaveiro do SO está indisponível; os segredos não podem ser armazenados.",
    th: "พวงกุญแจระบบปฏิบัติการไม่พร้อมใช้งาน ไม่สามารถจัดเก็บข้อมูลลับได้",
    "zh-CN": "操作系统密钥链不可用；无法存储密钥。",
    "zh-TW": "作業系統金鑰鏈無法使用；無法儲存密鑰。",
  },
};

// Map locale codes to filenames
const localeFiles = {
  de: "de.json",
  es: "es.json",
  "es-MX": "es-MX.json",
  fr: "fr.json",
  id: "id.json",
  it: "it.json",
  ja: "ja.json",
  ko: "ko.json",
  "pt-BR": "pt-BR.json",
  th: "th.json",
  "zh-CN": "zh-CN.json",
  "zh-TW": "zh-TW.json",
};

function setNestedValue(obj, path, value) {
  const keys = path.split(".");
  let current = obj;
  for (let i = 0; i < keys.length - 1; i++) {
    if (!current[keys[i]]) {
      current[keys[i]] = {};
    }
    current = current[keys[i]];
  }
  current[keys[keys.length - 1]] = value;
}

// Process each locale
for (const [locale, filename] of Object.entries(localeFiles)) {
  const filePath = resolve(localesDir, filename);
  const json = JSON.parse(readFileSync(filePath, "utf-8"));

  let addedCount = 0;
  for (const [keyPath, translationMap] of Object.entries(allTranslations)) {
    const value = translationMap[locale];
    if (value !== undefined) {
      setNestedValue(json, keyPath, value);
      addedCount++;
    }
  }

  writeFileSync(filePath, JSON.stringify(json, null, 2) + "\n", "utf-8");
  console.log(`[${locale}] Added ${addedCount} keys to ${filename}`);
}

// Sort keys alphabetically within each namespace (matching English key order)
function sortJsonKeys(obj) {
  if (Array.isArray(obj)) return obj;
  if (obj === null || typeof obj !== "object") return obj;

  const sorted = {};
  const keys = Object.keys(obj).sort((a, b) => a.localeCompare(b, "en"));
  for (const key of keys) {
    sorted[key] = sortJsonKeys(obj[key]);
  }
  return sorted;
}

// Also sort the en.json file to ensure it matches
const enPath = resolve(localesDir, "en.json");
const enJson = JSON.parse(readFileSync(enPath, "utf-8"));
// Check if all keys already exist in en.json
let enMissing = 0;
for (const keyPath of Object.keys(allTranslations)) {
  const keys = keyPath.split(".");
  let current = enJson;
  let missing = false;
  for (const k of keys) {
    if (current[k] === undefined) {
      missing = true;
      break;
    }
    current = current[k];
  }
  if (missing) {
    enMissing++;
  }
}
if (enMissing > 0) {
  console.log(`[en] ${enMissing} keys missing from en.json (should already be present)`);
} else {
  console.log(`[en] All 46 keys already present in en.json`);
}

console.log("\nDone! All translations merged.");
